# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - uses: dart-lang/setup-dart@8a4b97ea2017cc079571daec46542f76189836b1 
    
    - name: Setup the flutter environment
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    
    - name: Get flutter dependencies
      run: flutter pub get
      
    - name: Publish
      run: dart pub publish --force
      
    # with:
    #   working-directory: path/to/package/within/repository
